Repository syncspot-team/Syncspot-FE, pull requests merged in 2025-03, with the labels that each got.

#189 [Design] 장소 투표하기 모바일 UI 구현
  src/components/common/kakao/KakaoMap.tsx
  src/pages/place/PlaceVotePage.tsx
Labels: 💄 Design

#191 [Design] 중간 지점 장소 추천화면 모바일 UI
  src/pages/location/LocationRecommendationsPage.tsx
Labels: 💄 Design

#194 [Design] 마이페이지 모바일 UI 구현
  src/components/users/UserChangePassword.tsx
  src/components/users/UserGroupList.tsx
  src/components/users/UserProfile.tsx
  src/components/users/UserProfileInfo.tsx
  src/components/users/UserQuit.tsx
  src/pages/users/UserPage.tsx
Labels: 💄 Design

#196 [Feature] 계정 삭제시 한번 더 묻도록 개선
  src/components/common/modal/QuitModal.tsx
  src/components/users/UserGroupList.tsx
  src/components/users/UserQuit.tsx
  src/pages/place/PlaceCreatePage.tsx
  src/pages/place/PlaceResultPage.tsx
  src/pages/place/PlaceVotePage.tsx
  src/types/modalType.ts
Labels: ✨ Feature

#190 [Design] 모바일 UI 시간 투표하기 바텀시트, 투표결과 그리드
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/time/resultTime/gridTime.tsx
  src/components/time/resultTime/voteResultGrid.tsx
  src/components/time/utils/formatTime.ts
  src/components/time/voteTime/VoteResultByDate.tsx
  src/components/time/voteTime/clickCalendar.tsx
  src/components/time/voteTime/datePicker.tsx
  src/components/time/voteTime/myVote.tsx
  src/components/time/voteTime/timeSelect.css
  src/components/time/voteTime/timeSelect.tsx
  src/components/time/voteTime/timeSelectBox.tsx
  src/pages/time/TimeResultPage.tsx
  src/pages/time/TimeVotePage.tsx
  src/types/modalType.ts
  src/types/time/timeProps.ts
Labels: 💄 Design

#197 [Fix] 반응형 css 수정
  src/components/common/modal/ShareMeetingModal.tsx
  src/components/layout/header/DesktopMenu.tsx
  src/components/layout/header/MobileMenu.tsx
  src/components/layout/shareModal/Copied.tsx
  src/components/layout/shareModal/EmailButton.tsx
  src/components/layout/shareModal/EmailInput.tsx
  src/components/layout/shareModal/Kakao.tsx
  src/components/time/voteTime/VoteResultByDate.tsx
  src/components/time/voteTime/datePicker.tsx
  src/hooks/share/useRenderShareButton.ts
  src/pages/location/LocationEnterPage.tsx
  src/pages/place/PlaceCreatePage.tsx
  src/pages/place/PlaceVotePage.tsx
  src/pages/time/TimeCreatePage.css
  src/pages/time/TimeCreatePage.tsx
  src/pages/time/TimeResultPage.tsx
  src/pages/time/TimeVotePage.tsx
  src/utils/renderShareButton.ts
Labels: 💄 Design, 🔨 Fix

#198 [Design] 서비스 소개 모바일 UI 구현
  src/assets/icons/IconAboutSyncspot.svg
  src/assets/icons/IconBubbleOne.svg
  src/assets/icons/IconBubbleTwo.svg
  src/assets/icons/IconMobileMidpoint.svg
  src/assets/icons/IconMobilePlaceVote.svg
  src/assets/icons/IconMobileTimeVote.svg
  src/pages/about/AboutPage.tsx
Labels: 💄 Design

#208 [Feature] 소셜 로그인 비밀번호 변경 여부 처리
  src/assets/icons/IconMobileMidpoint.png
  src/assets/icons/IconMobileMidpoint.svg
  src/components/layout/header/MobileMenuList.tsx
  src/components/users/DesktopSideMenu.tsx
  src/components/users/MobileSideMenu.tsx
  src/pages/about/AboutPage.tsx
  src/types/users/getUserInfoResponseType.ts
Labels: ✨ Feature

#203 [Fix] 시간투표 생성 UI 수정
  src/assets/icons/IconTimeDropdown.svg
  src/assets/icons/IconTriangle.svg
  src/components/common/modal/Modal.tsx
  src/components/common/modal/RecreateVoteModal.tsx
  src/components/layout/header/DesktopMenu.tsx
  src/components/layout/header/MobileMenuList.tsx
  src/components/layout/shareModal/EmailInput.tsx
  src/components/time/resultTime/voteResultGrid.tsx
  src/components/time/voteTime/datePicker.tsx
  src/components/time/voteTime/myVote.tsx
  src/components/time/voteTime/timeSelect.css
  src/components/time/voteTime/timeSelect.tsx
  src/components/time/voteTime/timeSelectBox.tsx
  src/hooks/header/useMenuItems.ts
  src/pages/place/PlaceResultPage.tsx
  src/pages/time/TimeCreatePage.css
  src/pages/time/TimeCreatePage.tsx
  src/pages/time/TimeResultPage.tsx
  src/state/mutations/time/usePostTimeRoomMutation.ts
  src/state/mutations/time/usePostTimeVoteMutation.ts
  src/state/mutations/time/usePutTimeRoomMutation.ts
  src/state/mutations/time/usePutTimeVoteMutation.ts
  src/state/queries/time/key.ts
  src/state/queries/time/useGetTimeDatesQuery.ts
  src/state/queries/time/useGetTimeResultQuery.ts
  src/state/queries/time/useGetTimeVotedQuery.ts
  src/types/shareType.ts
  src/types/time/timeProps.ts
Labels: 💄 Design, 🔨 Fix

#215 design: 디자인 QA
  src/components/location/Pagination.tsx
  src/components/location/PlaceItem.tsx
  src/components/time/resultTime/voteResultGrid.tsx
  src/components/time/voteTime/VoteResultByDate.tsx
  src/components/time/voteTime/clickCalendar.tsx
  src/components/time/voteTime/datePicker.tsx
  src/components/time/voteTime/myVote.tsx
  src/components/time/voteTime/timeSelect.css
  src/components/time/voteTime/timeSelectBox.tsx
  src/components/users/DesktopSideMenu.tsx
  src/components/users/UserChangePassword.tsx
  src/components/users/UserProfileInfo.tsx
  src/pages/about/AboutPage.tsx
  src/pages/location/LocationRecommendationsPage.tsx
  src/pages/place/PlaceResultPage.tsx
  src/pages/time/TimeCreatePage.css
  src/pages/time/TimeCreatePage.tsx
  src/pages/time/TimeResultPage.tsx
  src/pages/time/TimeVotePage.tsx
Labels: 💄 Design, 🔨 Fix

#211 [Refactor] 중간 지점 장소 입력 리팩토링
  src/components/layout/header/ShareButton.tsx
  src/components/location/LocationEnterPage/DesktopLocationEnter.tsx
  src/components/location/LocationEnterPage/FriendLocationList.tsx
  src/components/location/LocationEnterPage/LocationActionButtons.tsx
  src/components/location/LocationEnterPage/LocationContext.tsx
  src/components/location/LocationEnterPage/MobileLocationEnter.tsx
  src/components/location/LocationEnterPage/MyLocationList.tsx
  src/hooks/location/useAutoScroll.ts
  src/hooks/location/useLocationData.ts
  src/hooks/location/useLocationForm.ts
  src/hooks/location/useLocationInitialization.ts
  src/hooks/location/useLocationMutations.ts
  src/hooks/useDeviceType.ts
  src/pages/location/LocationEnterPage.tsx
Labels: ♻️ Refactor

#218 [Design] 카톡 공유 이미지 수정
  index.html
  src/components/layout/shareModal/EmailInput.tsx
  src/components/time/resultTime/voteResultGrid.tsx
  src/components/time/utils/fillGridColors.ts
  src/hooks/share/useKakaoShare.ts
  src/utils/renderShareButton.ts
Labels: 💄 Design
