Repository syncspot-team/Syncspot-FE, pull requests merged in 2025-02, with the labels that each got.

#111 [Design] 서비스 소개 페이지 UI
  src/assets/icons/IconAboutInstagram.svg
  src/assets/icons/IconAboutIphone.png
  src/assets/icons/IconAboutMap.svg
  src/assets/icons/IconAboutPlaceSearch.png
  src/assets/icons/IconAboutSpot.png
  src/assets/icons/IconAboutTimeVote.png
  src/assets/icons/IconGithub.svg
  src/assets/icons/IconSmallDolphin.svg
  src/components/layout/header/RoomList.tsx
  src/pages/about/AboutPage.tsx
  src/styles/global.css
Labels: ✨ Feature, 💄 Design

#114 [Feature] RoomList 연동
  src/components/auth/PwInquiryStep.tsx
  src/components/layout/header/AuthButton.tsx
  src/components/layout/header/DesktopMenu.tsx
  src/components/layout/header/DesktopSubMenu.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/HeaderMenu.tsx
  src/components/layout/header/MainLogo.tsx
  src/components/layout/header/MobileMenu.tsx
  src/components/layout/header/MobileMenuList.tsx
  src/components/layout/header/MobileSubMenu.tsx
  src/components/layout/header/RoomList.tsx
  src/components/layout/header/RoomListItem.tsx
  src/constants/api.ts
  src/hooks/header/useMenuItems.ts
  src/hooks/header/useNavigateWithRoomCheck.ts
  src/hooks/useClickOutside.ts
  src/hooks/useResponsiveClose.ts
  src/pages/auth/HelpPwInquiryPage.tsx
  src/pages/auth/SignInPage.tsx
  src/pages/auth/SignUpPage.tsx
  src/types/header/menuItemType.ts
Labels: ✨ Feature

#115 [Feature] 온보딩 api 연동
  src/apis/header/getJoinRoom.ts
  src/apis/onboarding/getRoomDetailInfo.ts
  src/apis/onboarding/patchRoomMemo.ts
  src/apis/onboarding/patchRoomName.ts
  src/apis/onboarding/postSaveUserToRoom.ts
  src/components/common/modal/RoomDetailInfoModal.tsx
  src/components/layout/header/MobileMenu.tsx
  src/components/layout/header/MobileMenuList.tsx
  src/components/layout/header/RoomList.tsx
  src/components/layout/header/RoomListItem.tsx
  src/components/onboarding/FunctionOption.tsx
  src/components/onboarding/OnBoardingCreate.tsx
  src/components/onboarding/OnBoardingFunctionSelect.tsx
  src/components/onboarding/OnBoardingPlan.tsx
  src/components/onboarding/modal/EditableField.tsx
  src/constants/api.ts
  src/hooks/header/useMenuItems.ts
  src/hooks/header/useNavigateWithRoomCheck.ts
  src/pages/about/AboutPage.tsx
  src/pages/location/LocationEnterPage.tsx
  src/pages/onboarding/OnBoardingPage.tsx
  src/state/mutations/auth/useSignInMutation.ts
  src/state/mutations/onboarding/useCreateRoomMutation.ts
  src/state/mutations/onboarding/usePatchRoomMemoMutation.ts
  src/state/mutations/onboarding/usePatchRoomNameMutation.ts
  src/state/mutations/onboarding/useSaveUserToRoomMutation.ts
  src/state/queries/header/useGetJoinRoomQuery.ts
  src/state/queries/location/useGetPlaceSearchQuery.ts
  src/state/queries/onboarding/key.ts
  src/state/queries/onboarding/useGetRoomDetailInfoQuery.ts
  src/state/store/loginStore.ts
  src/state/store/roomIdStore.ts
  src/state/store/roomStore.ts
  src/types/location/placeSearchResponseType.ts
  src/types/onboarding/createRoomRequestType.ts
  src/types/onboarding/getRoomDetailInfoResponseType.ts
  src/types/onboarding/patchRoomMemoRequestType.ts
  src/types/onboarding/patchRoomNameRequestType.ts
Labels: ✨ Feature

#117 [Feature] 중간 지점 장소 입력 api 연동
  src/apis/common/getJoinedRoomCheck.ts
  src/components/common/kakao/KakaoLocationPicker.tsx
  src/components/common/routes/RoomCheck.tsx
  src/components/layout/RoomLayout.tsx
  src/components/layout/header/RoomList.tsx
  src/pages/auth/SignUpPage.tsx
  src/pages/location/LocationEnterPage.tsx
  src/pages/location/LocationRecommendationsPage.tsx
  src/pages/location/LocationResultPage.tsx
  src/pages/place/PlaceCreatePage.tsx
  src/routes/AppRouter.tsx
  src/state/queries/common/key.ts
  src/state/queries/common/useGetJoinedRoomCheckQuery.ts
  src/state/queries/location/useGetPlaceSearchQuery.ts
  src/types/common/joinedRoomCheckResponseType.ts
Labels: ✨ Feature

#118 [Feature] 중간 지점 결과 화면 api 연동
  src/apis/location/getMidpointSearch.ts
  src/apis/location/getMidpointTimeSearch.ts
  src/components/common/kakao/KakaoMap.tsx
  src/components/location/AddressDisplay.tsx
  src/components/location/MidpointListItem.tsx
  src/components/location/constants/index.ts
  src/constants/api.ts
  src/hooks/location/useCoordinates.ts
  src/pages/location/LocationEnterPage.tsx
  src/pages/location/LocationResultPage.tsx
  src/state/mutations/location/usePlaceDeleteMutation.ts
  src/state/mutations/location/usePlaceSaveMutation.ts
  src/state/mutations/location/usePlaceUpdateMutation.ts
  src/state/queries/location/key.ts
  src/state/queries/location/useMidpointSearchQuery.ts
  src/state/queries/location/useMidpointTimeSearchQuery.ts
  src/types/location/midpointSearchResponseType.ts
  src/types/location/midpointTimeSearchResponseType.ts
Labels: ✨ Feature

#119 [Feature] 장소 추천 화면 api 연동
  src/apis/location/getRecommendPlaceSearch.ts
  src/components/common/kakao/KakaoMap.tsx
  src/components/location/AddressDisplay.tsx
  src/components/location/MidpointListItem.tsx
  src/components/location/Pagination.tsx
  src/components/location/PlaceItem.tsx
  src/components/location/PlaceList.tsx
  src/components/location/PlaceTypeFilter.tsx
  src/components/location/constants/index.ts
  src/pages/location/LocationRecommendationsPage.tsx
  src/pages/location/LocationResultPage.tsx
  src/state/mutations/location/usePlaceDeleteMutation.ts
  src/state/mutations/location/usePlaceSaveMutation.ts
  src/state/mutations/location/usePlaceUpdateMutation.ts
  src/state/queries/location/key.ts
  src/state/queries/location/useGetRecommendPlaceSearchQuery.ts
  src/types/location/recommendPlaceSearchResponseType.ts
Labels: ✨ Feature, ♻️ Refactor

#121 [Design] 장소 입력 및 카카오 맵 등의 UI 일부 수정
  src/components/common/kakao/KakaoMap.tsx
  src/components/location/MidpointListItem.tsx
  src/components/location/PlaceItem.tsx
  src/hooks/location/useCoordinates.ts
  src/pages/location/LocationEnterPage.tsx
  src/pages/location/LocationRecommendationsPage.tsx
  src/pages/location/LocationResultPage.tsx
Labels: 💄 Design

#123 [Feature] 장소 투표 생성 api 연동
  src/apis/place/getPlaceVoteRoomCheck.ts
  src/apis/place/postPlaceVoteRoomCreate.ts
  src/apis/place/putPlaceVoteRoomUpdate.ts
  src/components/common/routes/RoomCheck.tsx
  src/components/location/MidpointListItem.tsx
  src/components/location/PlaceItem.tsx
  src/components/onboarding/OnBoardingPlan.tsx
  src/pages/location/LocationEnterPage.tsx
  src/pages/location/LocationRecommendationsPage.tsx
  src/pages/location/LocationResultPage.tsx
  src/pages/place/PlaceCreatePage.tsx
  src/state/mutations/place/usePlaceVoteRoomCreateMutation.ts
  src/state/mutations/place/usePlaceVoteRoomUpdateMutation.ts
  src/state/queries/location/useGetPlaceSearchQuery.ts
  src/state/queries/location/useGetRecommendPlaceSearchQuery.ts
  src/state/queries/location/useMidpointSearchQuery.ts
  src/state/queries/place/key.ts
  src/state/queries/place/useGetPlaceVoteRoomCheckQuery.ts
  src/types/place/placeVoteRoomCheckResponseType.ts
  src/types/place/placeVoteRoomCreateRequestType.ts
  src/types/place/placeVoteRoomUpdateRequestType.ts
Labels: ✨ Feature

#125 [Fix] 중간 지점 결과 화면 로직 수정
  src/components/location/MidpointListItem.tsx
  src/hooks/location/useCoordinates.ts
  src/pages/location/LocationResultPage.tsx
Labels: 🔨 Fix

#127 [Feature] 장소 투표 결과화면 api 연동
  src/apis/place/getPlaceVoteResult.ts
  src/pages/place/PlaceResultPage.tsx
  src/state/mutations/place/usePlaceRevoteMutation.ts
  src/state/mutations/place/usePlaceVoteMutation.ts
  src/state/mutations/place/usePlaceVoteRoomUpdateMutation.ts
  src/state/queries/place/key.ts
  src/state/queries/place/useGetPlaceVoteResultQuery.ts
  src/types/place/placeVoteResultResponseType.ts
Labels: ✨ Feature

#122 [FEAT] 시간투표하기•결과 UI, api, query, mutation
  src/apis/time/getTimeDates.ts
  src/apis/time/getTimeResult.ts
  src/apis/time/getTimeVoted.ts
  src/apis/time/postTimeRoom.ts
  src/apis/time/postTimeVote.ts
  src/apis/time/putTimeRoom.ts
  src/apis/time/putTimeVote.ts
  src/assets/icons/IconTimeDropdown.svg
  src/assets/icons/IconTriangle.svg
  src/components/resultTime/gridTime.tsx
  src/components/resultTime/voteResultGrid.tsx
  src/components/voteTime/clickCalendar.css
  src/components/voteTime/clickCalendar.tsx
  src/components/voteTime/datePicker.tsx
  src/components/voteTime/myVote.tsx
  src/components/voteTime/timeSelect.css
  src/components/voteTime/timeSelect.tsx
  src/components/voteTime/timeSelectBox.tsx
  src/pages/time/TimeResultPage.tsx
  src/pages/time/TimeVotePage.tsx
  src/state/mutations/time/index.ts
  src/state/mutations/time/usePostTimeRoomMutation.ts
  src/state/mutations/time/usePostTimeVoteMutation.ts
  src/state/mutations/time/usePutTimeRoomMutation.ts
  src/state/mutations/time/usePutTimeVoteMutation.ts
  src/state/queries/time/index.ts
  src/state/queries/time/key.ts
  src/state/queries/time/useGetTimeDatesQuery.ts
  src/state/queries/time/useGetTimeResultQuery.ts
  src/state/queries/time/useGetTimeVotedQuery.ts
  src/types/time/GridColor.ts
  src/types/time/timeDatesResponseType.ts
  src/types/time/timeProps.ts
  src/types/time/timeResultType.ts
  src/types/time/timeRoomType.ts
  src/types/time/timeVoteType.ts
  src/types/time/timeVotedResponseType.ts
  src/utils/formatDate.ts
  src/utils/formatTime.ts
Labels: ✨ Feature, 💄 Design

#129 [Chore] components 폴더에 time 관심사 폴더 생성
  src/components/time/resultTime/gridTime.tsx
  src/components/time/resultTime/voteResultGrid.tsx
  src/components/time/voteTime/clickCalendar.css
  src/components/time/voteTime/clickCalendar.tsx
  src/components/time/voteTime/datePicker.tsx
  src/components/time/voteTime/myVote.tsx
  src/components/time/voteTime/timeSelect.css
  src/components/time/voteTime/timeSelect.tsx
  src/components/time/voteTime/timeSelectBox.tsx
  src/pages/time/TimeResultPage.tsx
  src/pages/time/TimeVotePage.tsx
Labels: ⚙️ Chore

#131 [Feature] 비밀번호 찾기 api 연동
  src/apis/auth/postPwReissue.ts
  src/apis/auth/postPwReissueEmailVerification.ts
  src/components/auth/PwInquiryStep.tsx
  src/components/auth/PwReissueStep.tsx
  src/constants/api.ts
  src/pages/auth/HelpPwInquiryPage.tsx
  src/state/mutations/auth/usePwReissueEmailVerificationMutation.ts
  src/state/mutations/auth/usePwReissueMutation.ts
  src/types/auth/PwReissueEmailVerificationRequestType.ts
  src/types/auth/PwReissueRequestType.ts
  src/utils/getErrorData.ts
Labels: ✨ Feature, ⚙️ Chore

#132 [Feature] 비밀번호 변경 api 연동
  src/apis/users/patchModifyPassword.ts
  src/components/common/modal/PasswordChangeModal.tsx
  src/components/users/DesktopSideMenu.tsx
  src/components/users/UserChangePassword.tsx
  src/components/users/UserProfile.tsx
  src/components/users/UserProfileImage.tsx
  src/components/users/UserProfileInfo.tsx
  src/components/users/UserQuit.tsx
  src/constants/api.ts
  src/pages/users/UserPage.tsx
  src/state/mutations/user/useModifyPasswordMutations.ts
  src/types/users/modifyPasswordRequestType.ts
Labels: ✨ Feature

#133 [Feature] 회원탈퇴 및 전체 모임 목록 연동
  src/apis/users/deleteQuitUser.ts
  src/components/users/UserGroupList.tsx
  src/components/users/UserProfileImage.tsx
  src/components/users/UserQuit.tsx
  src/constants/api.ts
  src/state/mutations/user/useQuitUserMutation.ts
  src/types/users/quitUserRequestType.ts
Labels: ✨ Feature

#139 [Feture] 추가 백엔드 api 연동 작업
  src/apis/users/getUserInfo.ts
  src/apis/users/getUserPresignedUrl.ts
  src/apis/users/getUserProfileImage.ts
  src/apis/users/patchUserAddress.ts
  src/apis/users/patchUserNickName.ts
  src/components/common/modal/RoomDetailInfoModal.tsx
  src/components/users/UserChangePassword.tsx
  src/components/users/UserGroupList.tsx
  src/components/users/UserProfile.tsx
  src/components/users/UserProfileImage.tsx
  src/components/users/UserProfileInfo.tsx
  src/constants/api.ts
  src/state/mutations/onboarding/useDeleteUserFromRoomMutation.ts
  src/state/mutations/user/usePatchUserAddressMutation.ts
  src/state/mutations/user/usePatchUserNickNameMutation.ts
  src/state/queries/header/useGetJoinRoomQuery.ts
  src/state/queries/users/key.ts
  src/state/queries/users/useGetUserInfoQuery.ts
  src/state/queries/users/useGetUserProfileImageQuery.ts
  src/types/onboarding/deleteUserFromRoomRequestType.ts
  src/types/users/getUserInfoResponseType.ts
  src/types/users/getUserPresignedUrlResponseType.ts
  src/types/users/getUserProfileImageResponseType.ts
  src/types/users/modifyUserAddressRequestType.ts
  src/types/users/modifyUserNicknameRequestType.ts
  src/utils/getErrorData.ts
Labels: ✨ Feature

#137 [Feat] 시간투표 연동, 반응형 렌더링
  src/components/onboarding/OnBoardingFunctionSelect.tsx
  src/components/time/resultTime/voteResultGrid.tsx
  src/components/time/utils/formatDate.ts
  src/components/time/utils/formatTime.ts
  src/components/time/voteTime/VoteResultByDate.tsx
  src/components/time/voteTime/clickCalendar.css
  src/components/time/voteTime/clickCalendar.tsx
  src/components/time/voteTime/datePicker.tsx
  src/components/time/voteTime/myVote.tsx
  src/components/time/voteTime/timeSelect.css
  src/components/time/voteTime/timeSelect.tsx
  src/components/time/voteTime/timeSelectBox.tsx
  src/pages/time/TimeCreatePage.css
  src/pages/time/TimeCreatePage.tsx
  src/pages/time/TimeResultPage.tsx
  src/pages/time/TimeVotePage.tsx
  src/state/mutations/time/usePostTimeRoomMutation.ts
  src/state/mutations/time/usePostTimeVoteMutation.ts
  src/state/mutations/time/usePutTimeRoomMutation.ts
  src/state/mutations/time/usePutTimeVoteMutation.ts
  src/state/queries/time/useGetTimeDatesQuery.ts
  src/state/queries/time/useGetTimeResultQuery.ts
  src/state/queries/time/useGetTimeVotedQuery.ts
  src/types/time/timeDatesResponseType.ts
  src/types/time/timeProps.ts
  src/types/time/timeResultType.ts
  src/types/time/timeVotedResponseType.ts
  src/utils/formatDate.ts
Labels: ✨ Feature, ♻️ Refactor, 💄 Design

#143 [Fix] 시간 투표, 결과 링크 접속시 제한
  src/pages/time/TimeResultPage.tsx
  src/pages/time/TimeVotePage.tsx
Labels: 🐛 Bug, 🔨 Fix

#145 [Fix] timevote 렌더링 문제, select 비동기 문제
  src/components/time/voteTime/clickCalendar.tsx
  src/components/time/voteTime/datePicker.tsx
  src/components/time/voteTime/myVote.tsx
  src/pages/time/TimeVotePage.tsx
  src/types/time/timeProps.ts
Labels: 🐛 Bug

#149 [BUG] 프로필 수정 중 에러 해결
  src/components/users/UserChangePassword.tsx
  src/components/users/UserProfileInfo.tsx
  src/types/modalType.ts
Labels: 🐛 Bug

#154 [Design] 에러 페이지 UI
  .pnp.cjs
  .yarn/cache/lottie-react-npm-2.4.1-91badf61e2-7f6a0a2cf2.zip
  index.html
  package.json
  src/App.tsx
  src/apis/instance.ts
  src/assets/icons/IconGithub.png
  src/assets/lotties/Lottie404.json
  src/assets/lotties/LottieGlobalLoading.json
  src/assets/lotties/LottieLoading.json
  src/assets/lotties/LottieSeachLocation.json
  src/components/common/input/Input.tsx
  src/components/error/boundary/APIErrorFallback.tsx
  src/components/error/boundary/UnknowErrorBoundary.tsx
  src/components/error/boundary/UnknowErrorFallback.tsx
  src/components/error/boundary/UnknownErrorBoundary.tsx
  src/components/error/boundary/UnknownErrorFallback.tsx
  src/components/layout/header/RoomList.tsx
  src/components/loading/GlobalLoading.tsx
  src/components/loading/Loading.tsx
  src/components/loading/SeachLocationLoading.tsx
  src/pages/auth/SignInPage.tsx
  src/pages/error/ErrorPage.tsx
  src/pages/error/SomethingWrongErrorPage.tsx
  src/routes/AppRouter.tsx
  yarn.lock
Labels: 🐛 Bug, ✨ Feature, 💄 Design

#156 [Feature] 랜더링 페이지 모바일 UI
  src/assets/icons/IconMenuAccount.svg
  src/assets/icons/IconMenuMidpoint.svg
  src/assets/icons/IconMenuPlace.svg
  src/assets/icons/IconMenuService.svg
  src/assets/icons/IconMenuTime.svg
  src/assets/icons/IconMobileMenuClose.svg
  src/components/common/input/Input.tsx
  src/components/layout/header/MobileMenu.tsx
  src/components/layout/header/MobileMenuList.tsx
  src/components/layout/header/MobileSubMenu.tsx
  src/components/layout/header/RoomList.tsx
  src/pages/landing/LandingPage.tsx
  src/styles/global.css
  src/utils/customTwMerge.ts
  tailwind.config.js
Labels: ✨ Feature

#160 [Feature] 회원가입 및 온보딩 모바일 UI 작업
  src/components/layout/header/MobileMenu.tsx
  src/components/layout/header/MobileMenuList.tsx
  src/components/layout/header/MobileSubMenu.tsx
  src/components/onboarding/OnBoardingCreate.tsx
  src/components/onboarding/OnBoardingFunctionSelect.tsx
  src/components/onboarding/OnBoardingPlan.tsx
  src/pages/auth/SignUpPage.tsx
  tailwind.config.js
Labels: ✨ Feature, 💄 Design

#162 [Feature] 마커 밀림 현상 개선
  src/components/common/kakao/KakaoMap.tsx
  src/components/error/boundary/UnknownErrorFallback.tsx
  src/components/loading/SearchLocationLoading.tsx
  src/components/location/MidpointListItem.tsx
  src/pages/location/LocationEnterPage.tsx
  src/pages/location/LocationResultPage.tsx
Labels: 🐛 Bug, ✨ Feature, 💄 Design

#165 [Fix] 장소투표 로직 관련 에러 해결
  src/components/common/kakao/KakaoMap.tsx
  src/components/common/modal/Modal.tsx
  src/components/place/PlaceCreateErrorPage.tsx
  src/components/place/PlaceVoteErrorPage.tsx
  src/pages/about/AboutPage.tsx
  src/pages/location/LocationEnterPage.tsx
  src/pages/place/PlaceCreatePage.tsx
  src/pages/place/PlaceVotePage.tsx
  src/state/queries/location/useMidpointSearchQuery.ts
Labels: 🐛 Bug, ✨ Feature, 💄 Design

#172 [Feature] kakao 공유하기
  index.html
  src/assets/icons/IconShare.svg
  src/assets/icons/IconShareBox.svg
  src/components/common/modal/ShareMeetingModal.tsx
  src/components/layout/header/DesktopMenu.tsx
  src/components/layout/header/MobileMenu.tsx
  src/components/layout/header/ShareButton.tsx
  src/hooks/useShare.ts
  src/pages/location/LocationEnterPage.tsx
  src/pages/place/PlaceCreatePage.tsx
  src/pages/place/PlaceVotePage.tsx
  src/types/mapAPIType.ts
  src/types/shareType.ts
  tailwind.config.js
Labels: ✨ Feature

#176 [Feature] 이메일 공유하기
  .github/workflows/cicd.yml
  .pnp.cjs
  .yarn/cache/@emailjs-browser-npm-4.4.1-64a2cb04f8-91c3d17028.zip
  index.html
  package.json
  src/assets/icons/IconInstagram.svg
  src/components/common/modal/ShareMeetingModal.tsx
  src/hooks/share/useEmailShare.ts
  src/hooks/share/useKakaoShare.ts
  yarn.lock
Labels: ✨ Feature

#182 [Design] 중간 지점 입력 모바일 UI
  src/components/common/bottomSheet/BottomSheet.tsx
  src/hooks/useBottomSheet.ts
  src/pages/location/LocationEnterPage.tsx
Labels: ✨ Feature, 💄 Design

#184 [Design] 중간 지점 결과 화면 모바일 UI
  src/pages/location/LocationResultPage.tsx
Labels: 💄 Design

#181 [Fix] 시간 투표값 드롭다운 변경 에러 해결
  src/components/layout/header/MobileMenu.tsx
  src/components/time/voteTime/clickCalendar.tsx
  src/components/time/voteTime/datePicker.tsx
  src/components/time/voteTime/myVote.tsx
  src/pages/time/TimeCreatePage.tsx
  src/pages/time/TimeVotePage.tsx
  src/state/mutations/time/usePutTimeRoomMutation.ts
  src/styles/global.css
Labels: 🐛 Bug, 🔨 Fix

#188 [Design] 장소 투표 생성 모바일 UI
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/layout/header/RoomList.tsx
  src/hooks/useBottomSheet.ts
  src/pages/location/LocationEnterPage.tsx
  src/pages/place/PlaceCreatePage.tsx
  src/state/mutations/place/usePlaceVoteMutation.ts
  src/state/mutations/place/usePlaceVoteRoomCreateMutation.ts
Labels: ✨ Feature, 💄 Design
