Repository syncspot-team/Syncspot-FE, pull requests merged in 2025-01, with the labels that each got.

#26 [Feature] 비동기 요청 함수 예시 작성
  .pnp.cjs
  .yarn/cache/jotai-npm-2.10.4-330b1df220-83dc754e0d.zip
  .yarn/cache/zustand-npm-5.0.2-35adcdc9f7-d9bb048d81.zip
  package.json
  src/apis/exam/exam.ts
  src/apis/instance.ts
  src/components/common/routes/PrivateRoute.tsx
  src/components/common/routes/PublicRoute.tsx
  src/pages/error/SomethingWrongErrorPage.tsx
  src/pages/landing/LandingPage.tsx
  src/routes/AppRouter.tsx
  src/state/queries/exam/key.ts
  src/state/queries/exam/useGetExamQuery.ts
  src/state/queries/index.tsx
  src/state/store/login.ts
  src/state/store/loginStore.ts
  yarn.lock
Labels: ✨ Feature

#28 [Chore] UI에 대한 경로 세팅
  src/components/layout/Layout.tsx
  src/components/layout/header/Header.tsx
  src/constants/path.ts
  src/pages/about/AboutPage.tsx
  src/pages/auth/HelpIdInquiryPage.tsx
  src/pages/auth/HelpPwInquiryPage.tsx
  src/pages/landing/LandingPage.tsx
  src/pages/location/LocationEnterPage.tsx
  src/pages/location/LocationRecommendationsPage.tsx
  src/pages/location/LocationResultPage.tsx
  src/pages/onboarding/OnBoardingPage.tsx
  src/pages/place/PlaceCreatePage.tsx
  src/pages/place/PlaceResultPage.tsx
  src/pages/place/PlaceVotePage.tsx
  src/pages/time/TimeCreatePage.tsx
  src/pages/time/TimeResultPage.tsx
  src/pages/time/TimeVotePage.tsx
  src/routes/AppRouter.tsx
  src/utils/getAPIResponseData.ts
Labels: ⚙️ Chore

#30 [Chore] api 경로 설정
  src/constants/api.ts
Labels: ⚙️ Chore

#32 [Feature] Header 구현
  src/apis/exam/exam.ts
  src/apis/header/getJoinRoom.ts
  src/apis/instance.ts
  src/assets/icons/IconDropdown.svg
  src/assets/icons/IconMainLogo.svg
  src/assets/icons/IconUser.svg
  src/components/common/toast/customToast.tsx
  src/components/layout/Layout.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/RoomList.tsx
  src/pages/landing/LandingPage.tsx
  src/routes/AppRouter.tsx
  src/state/queries/exam/key.ts
  src/state/queries/exam/useGetExamQuery.ts
  src/state/queries/header/key.ts
  src/state/queries/header/useGetJoinRoomQuery.ts
  src/state/store/loginStore.ts
  src/state/store/roomIdStore.ts
  src/styles/global.css
  src/types/header/joinRoomResponseType.ts
  src/utils/getAPIResponseData.ts
  tailwind.config.js
Labels: ✨ Feature

#34 [Feature] 로그인 화면 구현
  .pnp.cjs
  .yarn/cache/@hookform-resolvers-npm-3.9.1-f46d34e57e-8a4056db38.zip
  .yarn/cache/property-expr-npm-2.0.6-2a0857ed05-69b7da1503.zip
  .yarn/cache/react-hook-form-npm-7.54.2-9e7394f4c4-6eebead290.zip
  .yarn/cache/tiny-case-npm-1.0.3-8c9747c74e-c0cbed3588.zip
  .yarn/cache/toposort-npm-2.0.2-d472329c7d-ab9ca91fce.zip
  .yarn/cache/type-fest-npm-2.19.0-918b953248-a5a7ecf2e6.zip
  .yarn/cache/yup-npm-1.6.1-e90c4f7113-84c2b53996.zip
  package.json
  src/apis/auth/postSignIn.ts
  src/assets/icons/IconAntenna.svg
  src/assets/icons/IconOauthGoogle.svg
  src/assets/icons/IconOauthKakao.svg
  src/assets/icons/IconOauthNaver.svg
  src/components/common/Buttons/Button.tsx
  src/components/common/Buttons/LoginButton/LoginButton.tsx
  src/components/common/toast/customToast.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/RoomList.tsx
  src/pages/auth/SignInPage.tsx
  src/pages/landing/LandingPage.tsx
  src/state/mutations/auth/useSignInMutation.ts
  src/state/mutations/indext.tsx
  src/state/queries/header/useGetJoinRoomQuery.ts
  src/state/store/loginStore.ts
  src/types/auth/SignInRequestType.ts
  src/types/auth/SignInResponseType.ts
  src/utils/customTwMerge.ts
  tailwind.config.js
  yarn.lock
Labels: ✨ Feature

#36 [Fix] Auth버튼 경로 문제 해결
  src/components/common/button/AuthButton.tsx
  src/components/common/button/Button.tsx
  src/pages/auth/SignInPage.tsx
  tsconfig.app.json
  tsconfig.node.json
Labels: 🔨 Fix

#41 [Feature] 회원가입
  index.html
  src/apis/auth/postSignUp.ts
  src/components/common/input/Input.tsx
  src/pages/auth/SignUpPage.tsx
  src/state/mutations/auth/useSignUpMutation.ts
  src/types/auth/SignUpRequestType.ts
  src/types/kakaoMap.ts
  src/utils/validatePw.ts
Labels: ✨ Feature

#48 [Fix] 온보딩 페이지 코드리뷰 반영
  src/apis/onboarding/postCreateRoom.ts
  src/components/onboarding/OnBoardingCreate.tsx
  src/pages/auth/SignInPage.tsx
  src/state/mutations/auth/useSignInMutation.ts
  src/state/mutations/onboarding/useCreateRoomMutation.ts
Labels: 🔨 Fix

#49 [Feature] 중간 지점 장소 입력 UI 구현
  index.html
  public/marker.svg
  public/selectedMarker.svg
  src/apis/kakao/searchAddressInfo.ts
  src/apis/kakao/searchPlacesByKeyword.ts
  src/apis/kakaoInstance.ts
  src/assets/icons/IconEditPen.svg
  src/assets/icons/IconXmark.svg
  src/components/common/button/SearchButton.tsx
  src/components/common/kakao/KakaoLocationPicker.tsx
  src/components/common/kakao/KakaoLocationSearch.tsx
  src/components/common/kakao/KakaoMap.tsx
  src/components/common/kakao/types.ts
  src/components/common/modal/KakaoLocationModal.tsx
  src/components/onboarding/OnBoardingPlan.tsx
  src/components/onboarding/RoomInfo.tsx
  src/hooks/index.tsx
  src/hooks/useDebounce.ts
  src/pages/auth/SignUpPage.tsx
  src/pages/location/LocationEnterPage.tsx
  src/types/kakao/searchAddressInfoResponseType.ts
  src/types/kakao/searchPlacesByKeywordResponseType.ts
  src/types/mapAPIType.ts
Labels: ✨ Feature

#52 [Fix] 맵 렌더링 관련 에러 해결
  src/components/common/kakao/KakaoMap.tsx
  src/pages/location/LocationEnterPage.tsx
  src/types/mapAPIType.ts
Labels: 🔨 Fix

#55 [Feature] 장소 입력 로직 수정
  src/components/common/button/SearchButton.tsx
  src/components/common/kakao/KakaoLocationPicker.tsx
  src/pages/auth/SignUpPage.tsx
  src/pages/location/LocationEnterPage.tsx
Labels: ✨ Feature

#60 [Refactor] 헤더 부분 개선
  src/assets/icons/IconHamburgerMenu.svg
  src/assets/icons/IconHeaderXmark.svg
  src/components/layout/header/Header.tsx
  src/components/layout/header/HeaderMenu.tsx
  src/components/layout/header/RoomList.tsx
  src/pages/auth/SignUpPage.tsx
  src/pages/location/LocationEnterPage.tsx
Labels: ♻️ Refactor, 💄 Design

#61 [Feature] 중간 지점 장소 입력 부분 api 연동
  src/apis/auth/postSignUp.ts
  src/apis/header/getJoinRoom.ts
  src/apis/location/deletePlaceDelete.ts
  src/apis/location/getPlaceSearch.ts
  src/apis/location/patchPlaceUpdate.ts
  src/apis/location/postPlaceSave.ts
  src/constants/api.ts
  src/pages/location/LocationEnterPage.tsx
  src/state/mutations/location/usePlaceDeleteMutation.ts
  src/state/mutations/location/usePlaceSaveMutation.ts
  src/state/mutations/location/usePlaceUpdateMutation.ts
  src/state/queries/header/useGetJoinRoomQuery.ts
  src/state/queries/location/key.ts
  src/state/queries/location/useGetPlaceSearchQuery.ts
  src/types/location/placeSaveRequestType.ts
  src/types/location/placeSaveResponseType.ts
  src/types/location/placeSearchResponseType.ts
  src/types/location/placeUpdateRequestType.ts
Labels: ✨ Feature

#63 [Design] 중간 지점 찾기 결과 UI 구현
  src/assets/icons/IconLinkPin.svg
  src/assets/icons/IconRightHalfArrow.svg
  src/components/common/kakao/KakaoMap.tsx
  src/pages/location/LocationResultPage.tsx
Labels: 🐛 Bug, 💄 Design

#66 [Design] 중간 지점 장소 추천 결과화면 UI
  src/assets/icons/IconCafe.svg
  src/assets/icons/IconRestaurant.svg
  src/assets/icons/IconStudy.svg
  src/pages/location/LocationRecommendationsPage.tsx
  src/pages/location/LocationResultPage.tsx
Labels: 💄 Design

#68 [Design] 장소 투표 생성 및 투표 하기 UI
  src/pages/location/LocationEnterPage.tsx
  src/pages/place/PlaceCreatePage.tsx
  src/pages/place/PlaceVotePage.tsx
Labels: 💄 Design

#69 [Design] 장소 투표 결과 UI 구현
  src/pages/place/PlaceResultPage.tsx
Labels: 💄 Design

#72 [Design] 시간 투표 생성 UI
  .pnp.cjs
  .yarn/cache/@wojtekmaj-date-utils-npm-1.5.1-e21d58f022-7c213cca5a.zip
  .yarn/cache/get-user-locale-npm-2.3.2-3b463b4839-2796b3fc37.zip
  .yarn/cache/map-age-cleaner-npm-0.1.3-fd9e4b4aff-7495236c7b.zip
  .yarn/cache/mem-npm-8.1.1-4270f09409-5829c404d0.zip
  .yarn/cache/mimic-fn-npm-3.1.0-12d126ec66-a07cdd8ed6.zip
  .yarn/cache/p-defer-npm-1.0.0-4dfd0013f5-ed603c3790.zip
  .yarn/cache/react-calendar-npm-5.1.0-adf0168c42-27673f639c.zip
  .yarn/cache/warning-npm-4.0.3-291e921d6d-aebab44512.zip
  package.json
  src/pages/place/PlaceResultPage.tsx
  src/pages/time/TimeCreatePage.css
  src/pages/time/TimeCreatePage.tsx
  yarn.lock
Labels: 💄 Design

#96 [Refactor] 다른 버튼 컴포넌트도 공통 버튼 컴포넌트를 사용하도록 수정
  src/components/common/button/AddButton.tsx
  src/components/common/button/AuthButton.tsx
  src/components/common/button/NextButton.tsx
  src/components/common/button/SearchButton.tsx
  src/components/onboarding/FunctionOption.tsx
  src/components/onboarding/OnBoardingCreate.tsx
  src/components/onboarding/OnBoardingFunctionSelect.tsx
  src/components/onboarding/OnBoardingPlan.tsx
  src/pages/auth/SignInPage.tsx
  src/pages/auth/SignUpPage.tsx
  src/pages/location/LocationEnterPage.tsx
  src/pages/place/PlaceCreatePage.tsx
Labels: ♻️ Refactor

#98 Design/#97
  src/components/common/input/Input.tsx
  src/components/common/kakao/KakaoLocationPicker.tsx
  src/components/common/kakao/KakaoLocationSearch.tsx
  src/components/common/modal/KakaoLocationModal.tsx
Labels: ♻️ Refactor

#99 [Refactor] 공통 Input 컴포넌트를 사용하는 방식으로 수정
  src/components/common/button/Button.tsx
  src/components/common/input/Input.tsx
  src/components/common/kakao/KakaoLocationPicker.tsx
  src/components/onboarding/FunctionOption.tsx
  src/components/onboarding/OnBoardingCreate.tsx
  src/components/onboarding/OnBoardingPlan.tsx
  src/pages/auth/SignInPage.tsx
  src/pages/auth/SignUpPage.tsx
  src/pages/location/LocationEnterPage.tsx
  src/pages/place/PlaceCreatePage.tsx
  src/pages/place/PlaceResultPage.tsx
  src/pages/place/PlaceVotePage.tsx
Labels: ♻️ Refactor

#100 [Feature] 네이게이션 메뉴 드롭다운
  src/components/layout/header/Header.tsx
  src/components/layout/header/HeaderMenu.tsx
  src/components/layout/header/RoomList.tsx
Labels: ✨ Feature, 💄 Design

#101 [Design] 랜딩 페이지 UI
  src/assets/icons/IconRightHalfArrow.svg
  src/assets/images/LandingBackGroundImage.svg
  src/components/common/button/Button.tsx
  src/components/layout/header/RoomList.tsx
  src/pages/landing/LandingPage.tsx
  src/pages/location/LocationResultPage.tsx
  src/pages/onboarding/OnBoardingPage.tsx
  src/pages/place/PlaceVotePage.tsx
  tailwind.config.js
Labels: 💄 Design

#103 [Bug] 온보딩 단계에 따른 뒤로가기 문제 해결
  src/pages/landing/LandingPage.tsx
  src/pages/location/LocationEnterPage.tsx
  src/pages/onboarding/OnBoardingPage.tsx
Labels: 🐛 Bug

#104 [Feature] 모달 구현
  src/assets/icons/IconDetailInfo.svg
  src/assets/icons/IconDolphin.svg
  src/assets/icons/IconEmail.svg
  src/assets/icons/IconGhost.svg
  src/assets/icons/IconInstagram.svg
  src/components/common/button/Button.tsx
  src/components/common/modal/RecreateVoteModal.tsx
  src/components/common/modal/RoomDetailInfoModal.tsx
  src/components/common/modal/ShareMeetingModal.tsx
  src/components/layout/header/RoomList.tsx
  src/components/onboarding/OnBoardingPlan.tsx
  src/components/onboarding/RoomInfo.tsx
  src/hooks/useModal.ts
  src/pages/location/LocationEnterPage.tsx
  src/pages/place/PlaceCreatePage.tsx
  src/pages/place/PlaceResultPage.tsx
  src/types/modalType.ts
Labels: ✨ Feature, 💄 Design

#106 [Feature] 상세주소를 아래에 컴포넌트로 띄우도록 수정
  src/assets/icons/IconXmark.svg
  src/pages/location/LocationEnterPage.tsx
  src/pages/location/LocationRecommendationsPage.tsx
  src/pages/place/PlaceCreatePage.tsx
Labels: ✨ Feature

#109 [Design] 비밀번호 찾기 페이지 UI
  src/pages/auth/HelpIdInquiryPage.tsx
  src/pages/auth/HelpPwInquiryPage.tsx
  src/pages/auth/SignInPage.tsx
  src/routes/AppRouter.tsx
Labels: 💄 Design

#110 [Design] 마이페이지 UI
  src/assets/icons/IconAddressBook.svg
  src/assets/icons/IconEditTabler.svg
  src/assets/icons/IconLogout.svg
  src/assets/icons/IconUserQuit.svg
  src/assets/icons/IconWarningTriangle.svg
  src/components/auth/PwInquiryStep.tsx
  src/components/auth/PwReissueStep.tsx
  src/components/common/button/Button.tsx
  src/components/common/modal/PasswordChangeModal.tsx
  src/components/layout/header/HeaderMenu.tsx
  src/components/users/DesktopSideMenu.tsx
  src/components/users/MobileSideMenu.tsx
  src/components/users/SideMenuItem.tsx
  src/components/users/UserGroupList.tsx
  src/components/users/UserLogout.tsx
  src/components/users/UserProfile.tsx
  src/components/users/UserQuit.tsx
  src/components/users/constants/sideMenuItems.ts
  src/constants/path.ts
  src/pages/auth/HelpPwInquiryPage.tsx
  src/pages/auth/SignInPage.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/onboarding/OnBoardingPage.tsx
  src/pages/users/UserPage.tsx
  src/routes/AppRouter.tsx
  src/types/auth/PwInquiryStepType.ts
  src/types/modalType.ts
Labels: ✨ Feature, 💄 Design
